### ISSUE TITLE
Use a more standard approach for the pipeline step

### ISSUE THREAD

**Issue by zbynek** [jenkinsci/eiffel-broadcaster-plugin#118]
### What feature do you want to see added?

The way the pipeline step is implemented breaks the pipeline step docs for the `build` step (see https://github.com/jenkins-infra/jenkins.io/issues/7400). While it might be possible to make the pipeline step generator more robust, it's also worth considering to avoid using inheritance between pipeline steps, see
https://groups.google.com/g/jenkinsci-dev/c/WQIApQFbpio/m/JGg9uDelAgAJ
for suggestions.

**Comment by CJohanH** [comment]
The code that broke this was the [extension of BuildTriggerStep.DescriptorImpl](https://github.com/jenkinsci/eiffel-broadcaster-plugin/blob/eiffel-broadcaster-2.10.0/src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/pipeline/build/BuildWithEiffelStep.java#L75) that would return a new instance of the super class (e.g. BuildTriggerStep).


While not pretty (it never was while inherited either), I believe the remaining code that was extended can be copied as well to avoid this issue and retain the functionality as is.

**Comment by magnusbaeck** [comment]
What we believe is a fix for the problem has been released in 2.10.1 of the plugin. Thanks for reporting this, @zbynek!
