### ISSUE TITLE
Layout of purls in ArtC events & possible publishing of ArtP events

### ISSUE THREAD

**Issue by magnusbaeck** [jenkinsci/eiffel-broadcaster-plugin#3]
There are at least a couple of problems with the purls produced by the plugin:

* The artifact path follows immediately after "pkg:", making the purl syntactically invalid unless the artifacts happens to be stored in a subdirectory. According to the spec both the type and the name tokens are required, so if there's a slash in the artifact path it happens to be valid.
* The Jenkins server hostname isn't included anywhere in the purl so the point of usefulness of the build_path qualifier is limited.

Jenkins artifacts just aren't a good fit for purls since they're random files rather than consciously named packages, but we can at least produce syntactically valid purl strings.

Longer term I think we should consider publishing ArtP events with proper URLs so that we're not relying on pushing artifacts to other systems that produce ArtP events.

**Comment by Isacholm** [comment]
I agree, if the plugin has to send ArtC the purls should atleast be valid, any suggestion?

**Comment by Isacholm** [comment]
It's been descided at the latest eiffel-summit that this plugin should no longer send ArtC-events.
The main reason for this is the problem of propper purls.

**Comment by magnusbaeck** [comment]
I was about to close this issue in favor or #8, but realized that a build can't send both ArtC and ArtP events since the artifacts aren't actually published and available at the URIs announced in the event when the event is sent. We should definitely remove the current ArtC and ArtP publishing from this plugin, but long-term there should be a way for a build to publish ArtC and somehow tell this plugin the IDs of the ArtC events so that the plugin can publish the ArtP events when the artifacts are actually ready. For example, the build could store a file in the workspace that the plugin can read. I hope that'll actually work. We need to hook ourselves into the flow at such a point when the files are accessible.

**Comment by Isacholm** [comment]
I agree, I will close this issue and if it's useful, create a new one about publishing ArtC events.
