### ISSUE TITLE
job status code sometimes translates to Null

### ISSUE THREAD

**Issue by Isacholm** [jenkinsci/eiffel-broadcaster-plugin#4]
This issue happens in two cases. 
1. If the status code reported by jenkins is Null the plugin should set the outcome to INCONCLUSIVE in the eiffel-message. There is a bug so this doesn't happen. 
2.  If the status code reported by jenkins is not in the translation-table for status-codes.

This is an issue because the eiffel-protocol specifies a list of valid outcomes and "None" is not one of them. 

The easy fix for Nr 2 is to default every, to the plugin, unknown status code to "INCONCLUSIVE" but then there is a risk for status-codes to be missrepresented in the eiffel-message.

**Comment by magnusbaeck** [comment]
I thought this had been fixed the various refactoring that was done, but no. Here's a partial example of a log that was emitted by this plugin:

```
{
	"data": {
		"outcome": {
			"conclusion": null
		},
		"persistentLogs": [{
			"name": "Jenkins console log",
			"uri": "REDACTED"
		}]
	},
        ...
}
```

This was produced by a build that got the status NOT_BUILT, which I suppose is a case of the second item in the list above. I guess the remedy would be to produce a useful value for NOT_BUILT but also omit the conclusion key if it's null. I thought that was the default?

**Comment by SiRumCz** [comment]
In [Util.java](https://github.com/jenkinsci/eiffel-broadcaster-plugin/blob/2a5a0feb91dd23f43d81c296b1e2e12e228061a9/src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/Util.java#L207) you have:
```java
if (STATUS_TRANSLATION.get(status) == null) {
            statusTranslated = STATUS_TRANSLATION.get("inconclusive");
        } else {
            statusTranslated = STATUS_TRANSLATION.get(status);
        }
```

Which should cover all the cases (including `NOT_BUILT`), but since you used `STATUS_TRANSLATION.get("inconclusive")`, this will result to `null` value.
