### ISSUE TITLE
Add support for JCasC

### ISSUE THREAD

**Issue by magnusbaeck** [jenkinsci/eiffel-broadcaster-plugin#58]
### Dependencies

None.

### Feature Request

The plugin should obviously support [Jenkins Configuration as Code](https://www.jenkins.io/projects/jcasc/). The [guide to plugin developers](https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/PLUGINS.md) should contain enough information to make the plugin compatible, although I guess we should also make [EiffelBroadcasterConfig](https://github.com/jenkinsci/eiffel-broadcaster-plugin/blob/master/src/main/java/com/axis/jenkins/plugins/eiffel/eiffelbroadcaster/EiffelBroadcasterConfig.java) stop inheriting from hudson.Plugin.

**Comment by GLundh** [comment]
Hampus have made this migration for a bunch of our plugins, I recommend involving him to move this along quickly :)

**Comment by magnusbaeck** [comment]
I know! I'll try myself first but I certainly know who to contact if I run into problems.
