### ISSUE TITLE
Add possibility to add links to the ActT event

### ISSUE THREAD

**Issue by Isacholm** [jenkinsci/eiffel-broadcaster-plugin#9]
In the current version of the plugin there is no way of linking an existing event-id to the ArtT-event created by the plugin. To be able to link together eiffel-pipelines this is needed.

**Comment by magnusbaeck** [comment]
To elaborate a bit, we'll want to be able to have ActT events with CAUSE, CONTEXT, and/or FLOW_CONTEXT links. When a build is started as a downstream build within the same Jenkins instance we can inspect the causes and set up a correct CAUSE link (#11) and possibly copy CONTEXT and/or FLOW_CONTEXT links from that build, but when starting a build via APIs (typically REST) we need a way to supply event IDs that are added as links in the ActT event.
